package de.pedramnazari.simpletbg.tilemap.config;

import static de.pedramnazari.simpletbg.tilemap.model.TileType.*;

public final class LabyrinthMapConfig {

    private LabyrinthMapConfig() {
    }

    public static final int HERO_START_ROW = 1;
    public static final int HERO_START_COLUMN = 1;

    public static final int[][] MAP = new int[][]{
            {WALL.getType(), WALL.getType(), WALL.getType(), WALL.getType(), WALL.getType(), WALL.getType(), WALL.getType(), WALL.getType(), WALL.getType(), WALL.getType(), WALL.getType(), WALL.getType(), WALL.getType(), WALL.getType(), WALL.getType(), WALL.getType(), WALL.getType(), WALL.getType(), WALL.getType(), WALL.getType()},
            {WALL.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), WALL.getType()},
            {WALL.getType(), FLOOR1.getType(), WALL.getType(), WALL.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), WALL.getType(), FLOOR1.getType(), FLOOR1.getType(), WALL.getType(), FLOOR1.getType(), FLOOR1.getType(), WALL.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), WALL.getType(), FLOOR1.getType(), WALL.getType()},
            {WALL.getType(), FLOOR1.getType(), FLOOR1.getType(), WALL.getType(), FLOOR1.getType(), DESTRUCTIBLE_WALL.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), WALL.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), WALL.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), DESTRUCTIBLE_WALL.getType(), FLOOR1.getType(), WALL.getType()},
            {WALL.getType(), FLOOR1.getType(), FLOOR1.getType(), WALL.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), WALL.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), WALL.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), WALL.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), WALL.getType()},
            {WALL.getType(), FLOOR1.getType(), WALL.getType(), WALL.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), WALL.getType(), PORTAL.getType(), WALL.getType(), FLOOR1.getType(), WALL.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), WALL.getType(), FLOOR1.getType(), PORTAL.getType(), FLOOR1.getType(), WALL.getType()},
            {WALL.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), WALL.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), WALL.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), WALL.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), WALL.getType()},
            {WALL.getType(), FLOOR1.getType(), DESTRUCTIBLE_WALL.getType(), WALL.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), WALL.getType(), FLOOR1.getType(), WALL.getType(), FLOOR1.getType(), WALL.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), WALL.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), WALL.getType()},
            {WALL.getType(), FLOOR1.getType(), FLOOR1.getType(), WALL.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), WALL.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), WALL.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), WALL.getType()},
            {WALL.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), FLOOR1.getType(), EXIT.getType(), WALL.getType()},
            {WALL.getType(), WALL.getType(), WALL.getType(), WALL.getType(), WALL.getType(), WALL.getType(), WALL.getType(), WALL.getType(), WALL.getType(), WALL.getType(), WALL.getType(), WALL.getType(), WALL.getType(), WALL.getType(), WALL.getType(), WALL.getType(), WALL.getType(), WALL.getType(), WALL.getType(), WALL.getType()},
    };

    public static final int[][] ITEMS = new int[][]{
            {EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType()},
            {EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), HEALTH_POTION.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), POISON_POTION.getType(), EMPTY.getType(), EMPTY.getType()},
            {EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), WEAPON_SWORD.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType()},
            {EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), WEAPON_BOMB_PLACER.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType()},
            {EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), RING_MAGIC1.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType()},
            {EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), WEAPON_LANCE.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType()},
            {EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), HEALTH_POTION.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType()},
            {EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), POISON_POTION.getType(), EMPTY.getType(), EMPTY.getType()},
            {EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), WEAPON_MULTI_SPIKE_LANCE.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType()},
            {EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), HEALTH_POTION.getType(), EMPTY.getType(), EMPTY.getType()},
            {EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType()},
    };

    public static final int[][] ENEMIES = new int[][]{
            {EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType()},
            {EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType()},
            {EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), ENEMY_TD.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType()},
            {EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), ENEMY_LR.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType()},
            {EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), ENEMY_FH.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType()},
            {EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), ENEMY_TD.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), ENEMY_FH.getType(), EMPTY.getType()},
            {EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), ENEMY_2D.getType(), EMPTY.getType()},
            {EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), ENEMY_TD.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType()},
            {EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), ENEMY_TD.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType()},
            {EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType()},
            {EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType(), EMPTY.getType()},
    };
}
